### ISSUE TITLE
Support for windows + linux

### ISSUE THREAD

**Issue by alexreyes** [Alex-Neo-Projects/bagels#55]
Windows + Linux problems: 

- Bagels is using the intel macOS version of anvil by default

Windows specific problems: 
- Probably need to test paths

**Comment by alexreyes** [comment]
The main problem here is anvil. If we write a script to download the correct build of anvil for the user's computer, things should work on different platforms. 

Ways to test this: 
- testing that it works on intel macs: arch -x86_64 bagels
- testing that it works on linux: download a VM and try it out
- testing that it works on windows: download a VM or ask Erik to try it out 😩

**Comment by neocho** [comment]
working on [03198ab](https://github.com/Alex-Neo-Projects/bagels/commit/03198ab68970a4cebcef655b8df38f76e4e21df3)

**Comment by neocho** [comment]
no need for this since we swapped to ganache: working on [81c5f66](https://github.com/Alex-Neo-Projects/bagels/commit/81c5f668e5741b91ea3965791fdf02baa0a7dbf8)
