### ISSUE TITLE
Accept bytes as input for functions

### ISSUE THREAD

**Issue by alexreyes** [Alex-Neo-Projects/bagels#70]

**Comment by alexreyes** [comment]
Marking as `bug` (aka we need this by ETH Denver) b/c I think it's relatively common for contracts to take `bytes` types as input. 

I don't think it should be too hard to fix, I'll try it tomorrow

**Comment by neocho** [comment]
fixed here: c82f1bdb3a1a48edca921290039ddca3aeb37353
