### ISSUE TITLE
Presentation fixes

### ISSUE THREAD

**Issue by alexreyes** [Alex-Neo-Projects/bagels#75]
Fix output getting cut off: 
<img width="744" alt="Screenshot 2023-02-24 at 12 15 45 AM" src="https://user-images.githubusercontent.com/7016669/221127343-52456b70-0991-4364-8b82-73bfda60f99a.png">

Fix showing empty quotes:
<img width="349" alt="Screenshot 2023-02-24 at 12 16 00 AM" src="https://user-images.githubusercontent.com/7016669/221127386-fc91c744-4e5d-4a8b-973d-a339a600b0c8.png">

**Comment by alexreyes** [comment]
Empty quotes: 

```
// SPDX-License-Identifier: MIT
pragma solidity >0.8.0;

contract EthSocial {
  struct UserStruct { 
    string username; 
    uint age;
  }

  mapping (address => UserStruct) userStructs; 

  function getUser(address _addr) public view returns (UserStruct memory) { 
    return userStructs[_addr];
  }
}
```
call getUser() with bagels

**Comment by neocho** [comment]
keeping this open in case there's other bugs found
