### ISSUE TITLE
Show BigInts in the UI instead of floats

### ISSUE THREAD

**Issue by alexreyes** [Alex-Neo-Projects/bagels#76]
Example: 

![image](https://user-images.githubusercontent.com/7016669/221260520-b676eb48-ece5-42fa-b6d8-61f49447d7a6.png)

**Comment by neocho** [comment]
fixed this here [f73ef13](https://github.com/Alex-Neo-Projects/bagels/commit/f73ef13bdcd42a3ade8c3f0695c719777f5efc50). 

Removed ```parseInt()``` in ```parseOutputAndConvertToCorrectType()```
